export { default as commentController } from './commentController.js'
export { default as movieController } from './movieController.js'
export { default as showTimeController } from './showTimeController.js'
export { default as ticketController } from './ticketController.js'
export { default as userController } from './userController.js'